"""
pc_distinctive.py — two interpretability "gems" (NEW file).

(A) Distinctive features: the specific stylistic markers that separate Severian from
    John Chrysostom, per channel, ranked by a Welch t-statistic over the reference-
    standardised features. For the headline groups we report an alignment score --
    the correlation of the group's profile with the Severian-minus-Chrysostom
    discriminator vector -- so a positive value means the group carries Severian's
    markers, a negative value Chrysostom's.

(B) Rival distance: how confusable are the two rivals? Severian preached in
    Chrysostom's place and his homilies were absorbed into Chrysostom's corpus. We
    measure whether the two are unusually close in style (which would explain the
    historical confusion) via a leave-one-out discrimination accuracy and the rank of
    their centroid distance among all candidate-author pairs.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

from corpus_balance import balance_corpus
from ocr_source import derive_source

CHAN = {"FW": "$MFW$", "POS": "$POS$", "AFF": "$TRI$"}
SEV, CHRY = "pta0001", "pta0002"
PATRISTIC = ["pta0001", "pta0002", "pta0003", "pta0004", "pta0005", "pta0007", "pta0022"]
NAMES = {"pta0001": "Severian", "pta0002": "Chrysostom", "pta0003": "Eusebius",
         "pta0004": "Theodoret", "pta0005": "Cyril", "pta0007": "Origen", "pta0022": "Athanasius"}


def load():
    ref = balance_corpus(pd.read_csv("tlg-features.csv"), seed=0, min_works=4, cap_works=30)
    ref = ref[derive_source(ref).to_numpy() == "clean"].reset_index(drop=True)
    pc = pd.read_csv("pc-features.csv")
    return ref, pc


def zblock(ref, pc, prefix):
    cols = [c for c in ref.columns if c.startswith(prefix) and c in set(pc.columns)]
    X = ref[cols].fillna(0).to_numpy(float)
    mu, sd = X.mean(0), X.std(0); sd[sd == 0] = 1.0
    return cols, (X - mu) / sd, (pc[cols].fillna(0).to_numpy(float) - mu) / sd


def welch_t(a, b):
    return (a.mean(0) - b.mean(0)) / np.sqrt(a.var(0, ddof=1) / len(a) + b.var(0, ddof=1) / len(b) + 1e-12)


def write_table(fw_markers, path="paper/tables/distinctive.tex"):
    sev_top, chry_top = fw_markers
    lines = ["% auto-generated by pc_distinctive.py -- do not edit by hand",
             "\\begin{tabular}{ll}", "\\toprule",
             "Severian favours & John Chrysostom favours \\\\", "\\midrule"]
    for (ws, _), (wc, _) in zip(sev_top, chry_top):
        lines.append(f"\\gk{{{ws}}} & \\gk{{{wc}}} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    ref, pc = load()
    au = ref["author"].to_numpy()

    # ---- (A) distinctive features per channel ----
    print("=" * 70)
    print("(A) DISTINCTIVE FEATURES: Severian vs Chrysostom")
    fw_markers = None
    for ch, pref in CHAN.items():
        cols, Z, Zpc = zblock(ref, pc, pref)
        sev, chry = Z[au == SEV], Z[au == CHRY]
        t = welch_t(sev, chry)
        order = np.argsort(t)
        sev_top = [(cols[i].replace(pref, ""), t[i]) for i in order[::-1][:8]]
        chry_top = [(cols[i].replace(pref, ""), t[i]) for i in order[:8]]
        if ch == "FW":
            fw_markers = (sev_top, chry_top)
        print(f"\n-- {ch} --")
        print("  Severian markers  :", ", ".join(f"{w} ({v:+.1f})" for w, v in sev_top))
        print("  Chrysostom markers:", ", ".join(f"{w} ({v:+.1f})" for w, v in chry_top))

    write_table(fw_markers)
    print("\nwrote paper/tables/distinctive.tex")

    # alignment score for headline PCs (FW channel = interpretable words)
    cols, Z, Zpc = zblock(ref, pc, CHAN["FW"])
    disc = Z[au == SEV].mean(0) - Z[au == CHRY].mean(0)   # Severian - Chrysostom direction
    dn = disc / (np.linalg.norm(disc) + 1e-12)
    print("\nAlignment with the Severian\u2212Chrysostom axis (FW; + = Severian, \u2212 = Chrysostom):")
    for g in ["PC1", "PC21", "PC9", "PC16"]:
        v = Zpc[pc.index[pc["author"] == g].to_numpy()].mean(0)
        score = float(v @ dn / (np.linalg.norm(v) + 1e-12))
        print(f"  {g:>5}: {score:+.3f}")

    # ---- (B) rival distance ----
    print("\n" + "=" * 70)
    print("(B) RIVAL DISTANCE: how confusable are Severian and Chrysostom?")
    # combined z across channels
    blocks = [zblock(ref, pc, p)[1] for p in CHAN.values()]
    Zall = np.hstack(blocks)
    cent = {a: Zall[au == a].mean(0) for a in set(au)}

    # leave-one-out Severian-vs-Chrysostom discrimination
    correct = 0; total = 0
    for a, other in [(SEV, CHRY), (CHRY, SEV)]:
        idx = np.where(au == a)[0]
        for i in idx:
            n = len(idx)
            c_self = (cent[a] * n - Zall[i]) / (n - 1)
            d_self = np.abs(Zall[i] - c_self).mean()
            d_other = np.abs(Zall[i] - cent[other]).mean()
            correct += d_self < d_other; total += 1
    acc = correct / total
    print(f"  leave-one-out Severian/Chrysostom discrimination accuracy: {acc:.2f} ({total} works)")

    # rank of Sev-Chry centroid distance among all patristic pairs
    pairs = []
    cand = [a for a in PATRISTIC if a in cent]
    for i in range(len(cand)):
        for j in range(i + 1, len(cand)):
            d = np.abs(cent[cand[i]] - cent[cand[j]]).mean()
            pairs.append((NAMES[cand[i]], NAMES[cand[j]], d))
    pairs.sort(key=lambda x: x[2])
    sc = next(k for k, (a, b, d) in enumerate(pairs) if {a, b} == {"Severian", "Chrysostom"})
    print(f"  Severian\u2013Chrysostom centroid distance ranks {sc+1}/{len(pairs)} "
          f"(1 = most similar pair) among patristic candidates:")
    for a, b, d in pairs[:5]:
        star = "  <--" if {a, b} == {"Severian", "Chrysostom"} else ""
        print(f"     {a}\u2013{b}: {d:.3f}{star}")


if __name__ == "__main__":
    main()
